env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: nomad-vector-logger.bin
    id: nomad-vector-logger
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: .

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - config.sample.toml
